### ISSUE TITLE
No PostalCodes imported

### ISSUE THREAD

**Issue by fynjah** [coderholic/django-cities#106]
Hey! Thanks for app!

I've imported US.zip and everything is ok, except PostalCodes.. Zero records in this model.

What i do wrong? May you help me please.

    CITIES_FILES = {
        'city': {
           'filenames': ["US.zip",],
           'urls': ['http://download.geonames.org/export/dump/'+'{filename}']
        },
    }

    CITIES_PLUGINS = [
        'cities.plugin.reset_queries.Plugin', 
    ]

**Comment by coderholic** [comment]
Yeah you need to add...

```
CITIES_POSTAL_CODES = ['US']
```

See the readme for more details.

**Comment by fynjah** [comment]
Work like a charm. Thanks. Dunno why i missed this param.
