### ISSUE TITLE
CITIES_DATA_DIR setting not working

### ISSUE THREAD

**Issue by pramttl** [coderholic/django-cities#118]
This setting was introduced recently to allow changing the default directory where files are downloaded to in the local filesystem. (By default they are downloaded to `..site-packages/cities/data/`)

    CITIES_DATA_DIR='/var/data'

But I noticed that, even after having this setting configured in my settings.py file. The files were still downloaded to `/path/to/site-packages/cities/data/` instead of `/var/data` as defined by this setting.

**Comment by coderholic** [comment]
Did you install from github, or on older version from pip?

**Comment by pramttl** [comment]
@coderholic Oops, I used the pip version. That may be the reason.
