### ISSUE TITLE
Not adding all cities

### ISSUE THREAD

**Issue by mbaragiola** [coderholic/django-cities#124]
Hello,

I've encountered the following problem: Cities that are loaded in geonames.org, are not being loaded in my database.

For instance, the city of San Lorenzo, Santa Fe, Argentina has a population of 46.000, exists at geonames.org[0] but it isn't loaded to my database. This is just one case, there are many more.

Is this a bug or a misconfiguration of mine? I used default settings and then I tried explicitly setting both CITIES_IGNORE_EMPTY_REGIONS = False and CITIES_IGNORE_EMPTY_REGIONS = True, achieving the same result.

[0] http://www.geonames.org/search.html?q=San+Lorenzo%2C+Santa+Fe&country=AR

**Comment by blag** [comment]
Which San Lorenzo are you missing? The [PPL (populated place)](http://www.geonames.org/3948970/san-lorenzo.html) or the [PPLA2 (seat of a second-order administrative division)](http://www.geonames.org/3837097/san-lorenzo.html), or both?

**Comment by blag** [comment]
@mbaragiola Did you ever figure out if you were missing San Lorenzo the populated place (PPL) or San Lorenzo the second order administrative division (PPLA2)?

**Comment by mbaragiola** [comment]
@blag I'm so sorry, somehow I didn't see your reply. 

What I was missing was San Lorenzo PPL.

**Comment by blag** [comment]
I'll try to look into this later this week or next week. Ping me if I forget!

**Comment by blag** [comment]
@mbaragiola I just pushed version 0.5 to PyPI, which contains a bunch of fixes, including a bunch of new tests. Please upgrade to that version, rerun the import script, and check for the San Lorenzo PPL. If it's still an issue, I'll create a test for it and fix it.

Also, please see the testing section of the README to turn on debug logging so I can get a detailed report of what the import script did. Thanks!

**Comment by blag** [comment]
I'm going to close this due to inactivity. But if this isn't fixed in version 0.5 (and later) please post a comment back here and I will reopen this issue. Thanks!
