### ISSUE TITLE
Django 1.10 compatibility: AttributeError: type object 'BaseCommand' has no attribute 'option_list'` 

### ISSUE THREAD

**Issue by dpmontero** [coderholic/django-cities#127]
Hi,

I'm tried django-cities in Django 1.10, when I executed `python manage.py cities --import=all` I had a problem of compatibility version of Django
`File "....../env/local/lib/python2.7/site-packages/cities/management/commands/cities.py", line 55, in Command option_list = BaseCommand.option_list + (
AttributeError: type object 'BaseCommand' has no attribute 'option_list'`

**Comment by blag** [comment]
Should be fixed in 6998752f85242b8923973c7bc90eed50a7aa4a47. Can you test that by cloning this repo? That commit hasn't been pushed to PyPI yet. Thanks!

**Comment by dpmontero** [comment]
I continue with some problems:

1. Not exist `CITIES_IGNORE_EMPTY_REGIONS` in _conf_:
`  File ".../env/local/lib/python2.7/site-packages/cities/management/commands/cities.py", line 40, in <module>
    from ...conf import CITIES_IGNORE_EMPTY_REGIONS
ImportError: cannot import name CITIES_IGNORE_EMPTY_REGIONS
`

2. When I commented the line 40 of with `#from ...conf import CITIES_IGNORE_EMPTY_REGIONS`, this is the next message:
`./manage.py... or` 
`python manage.py cities --import=all
usage: manage.py cities [-h] [--version] [-v {0,1,2,3}] [--settings SETTINGS]
                        [--pythonpath PYTHONPATH] [--traceback] [--no-color]
manage.py cities: error: unrecognized arguments: --import=all
`

Thanks!!

**Comment by blag** [comment]
I think I've fixed the `CITIES_IGNORE_EMPTY_REGIONS` issue. Care to try again?

And I'm trying to add Travis CI tests to the repo so these sorts of issues don't keep popping up.

Thanks!

**Comment by dpmontero** [comment]
I think what there are not recognition command `import=all`:
I executed: `python manage.py cities --import=all`

```usage: manage.py cities [-h] [--version] [-v {0,1,2,3}] [--settings SETTINGS]
                        [--pythonpath PYTHONPATH] [--traceback] [--no-color]
manage.py cities: error: unrecognized arguments: --import=all
```

**Comment by dpmontero** [comment]
Ok!, thanks!

Now, uninstall and `pip install django-cities`, migrate with: `python manage.py migrate` appear this error:
`/env/local/lib/python2.7/site-packages/cities/migrations/0002_continent_models_and_foreign_keys.py", line 11, in <module>
    from ..conf import CONTINENT_DATA
ImportError: cannot import name CONTINENT_DATA
`

**Comment by dpmontero** [comment]
ok! Fixed!!

**Comment by blag** [comment]
I won't be around a computer to look into this until Monday, but I'll try to dig into it then.

Can you post the full stacktrace for me?

Thanks!

**Comment by dpmontero** [comment]
1.- I replaced the files and directories with your repository master.

2.- Made migrations. First: `python manage.py makemigrations`, second: `python manage.py migrate --fake cities`. All correct.

3.-  I executed `python manage.py cities --import=all`, 
the responsed message: `usage: manage.py cities [-h] [--version] [-v {0,1,2,3}] [--settings SETTINGS] [--pythonpath PYTHONPATH] [--traceback] [--no-color] manage.py cities: error: unrecognized arguments: --import=all`

That is like not to reconize de command `--import`. Is it relationated with the change [https://github.com/coderholic/django-cities/commit/6998752f85242b8923973c7bc90eed50a7aa4a47](url) ?

**Comment by blag** [comment]
You should NOT have to make migrations for Django-cities, that should already be done for you. There should be two migrations already created for you: 0001_initial and 0002_add continent_model_and_foreign_keys (or a similar name, I don't remember exactly what it is and I'm on mobile).

Additionally, unless you're upgrading from South, you shouldn't need to fake any of the migrations.

But that error, where it doesn't recognize the '--import' flag is rather weird. I'll have to dig into that on Monday. Thanks for the feedback!
