### ISSUE TITLE
Django 1.10 compatibility issue (BaseCommand.option_list) in ./manage.py cities

### ISSUE THREAD

**Issue by IwoHerka** [coderholic/django-cities#131]
Since `BaseCommand.option_list` was deprecated in Django 1.8 and removed in Django 1.10, `cities` command failes on `AttributeError: type object 'BaseCommand' has no attribute 'option_list'`.

**Comment by dpmontero** [comment]
Hi!,

You have the solution at #129 or I fixed it in [https://github.com/dpmontero/django-cities](https://github.com/dpmontero/django-cities)

**Comment by blag** [comment]
Fixed in #132, which was just merged. I'll close this once @coderholic cuts a new release to PyPI, but in the meantime you can use the `master` branch.
