### ISSUE TITLE
Where does Central America continent is?

### ISSUE THREAD

**Issue by erwinfeser** [coderholic/django-cities#134]
North, Central and South America are not really continents (entire America is), anyway I can see Central America countries but they are loaded as North America ones, which is wrong. All countries between Mexico and Colombia (not inclusive) and Caribbean islands belong to Central America.

**Comment by coderholic** [comment]
From https://en.wikipedia.org/wiki/Central_America:

> Central America is the southernmost, isthmian portion of the North American continent

From https://en.wikipedia.org/wiki/Continent:

> Ordered from largest in size to smallest, they are: Asia, Africa, North America, South America, Antarctica, Europe, and Australia.

In addition to that, we just import the data from geonames.org, we don't define it.

**Comment by blag** [comment]
@erwinfeser Believe it or not, there really isn't a universal standard for what constitutes a continent. Check out this section of the [Wikipedia page on Continents](https://en.wikipedia.org/wiki/Continent#Number) - sometimes North and South America are considered one continent, sometimes they're not. And to further compound the issue, different continent models are taught in different regions of the world!

But note that in every single continent model, Central America is considered part of North America.

And as @coderholic noted, we only take data from geonames.org - that's the appropriate place to take this discussion.

**Comment by coderholic** [comment]
That's correct. Central America isn't a continent. From
https://en.wikipedia.org/wiki/Central_America:

> Central America is the southernmost, isthmian portion of the North
American continent.
