### ISSUE TITLE
Postal codes are not being loaded

### ISSUE THREAD

**Issue by erwinfeser** [coderholic/django-cities#135]
I am using your master branch (commit a74e4e5f68a5669f581e65bda43c2bf862289d74) and:
Python 3.5.2
Django 1.10.2
(I tried the last version uploaded to pypi too, but that does not work with this Python/Django versions)

Import process seems to work fine, I do not see errors.
```python manage.py cities --import postal_code --force```
![screenshot from 2016-10-21 15-14-47](https://cloud.githubusercontent.com/assets/567788/19607573/2f1e1766-97a1-11e6-9f06-a4e4987934e7.png)

All tables are populated but I have 0 postal codes.

**Comment by erwinfeser** [comment]
PR: https://github.com/coderholic/django-cities/pull/136

**Comment by coderholic** [comment]
Zip codes aren't imported by default, you need to specify the countries
you'd like to import them for in the config file. See the readme.
