### ISSUE TITLE
search_names removed space

### ISSUE THREAD

**Issue by fuji246** [coderholic/django-cities#145]
Trying to search "san jose" but doesn't get any result, the search_names look like removed all spaces.

```
sqlite> select search_names from cities_light_city where "cities_light_city"."search_names" LIKE '%sanjose%';
sanjoseamerica sanjosecaliforniaamerica sanjosecaliforniarepublicamerica sanjosecaliforniarepublicunitedstates sanjosecaliforniarepublicunitedstatesofamerica sanjosecaliforniaunitedstates sanjosecaliforniaunitedstatesofamerica sanjosegoldenstateamerica sanjosegoldenstateunitedstates sanjosegoldenstateunitedstatesofamerica sanjosestateofcaliforniaamerica sanjosestateofcaliforniaunitedstates sanjosestateofcaliforniaunitedstatesofamerica sanjoseunitedstates sanjoseunitedstatesofamerica
southsanjosehillscaliforniaunitedstates southsanjosehillsunitedstates
```

**Comment by blag** [comment]
Judging from the names of your database tables you are using the Django-cities-light package and not this (just "Django-cities") package.

I think this is the project you want:

https://github.com/yourlabs/django-cities-light

Cheers!

**Comment by fuji246** [comment]
oops, sorry for the confusion

**Comment by blag** [comment]
No worries, we all make mistakes. Let me know if the D-C-L devs aren't responsive and I'll take a look at it for ya. :)
