### ISSUE TITLE
--import=PostalCode produces error.

### ISSUE THREAD

**Issue by donnaloia** [coderholic/django-cities#155]
Hi, I am having an issue when running the following in order.

python manage.py cities --import=country --force
Countries.objects.all().exclude(name='United States").delete()
python manage.py cities --import=city
python manage.py cities --import=postal_code
```

WARNING Postal code 99505 (United States) - invalid location ('', ''): could not convert string to float: 
null value in column "location" violates not-null constraint
web         | DETAIL:  Failing row contains (54, Jber, none, 99505, null, , Anchorage Municipality, , 6252001, null, null, null, null).
```
What is strange is I have been using Django-cities for almost two years and I have always ran a shell script with the lines above, and now for some reason it produces an error.

I have tried to reset and wipe database but still same error.

**Comment by blag** [comment]
Hi, contributor here. Can you answer a few questions for me:

* Which one of those commands is causing the error?
* What version of django-cities are you using?
* What's the full Python traceback?
* Does using an earlier version of django-cities allow you to cleanly import all of the data that you want? If so, which version was that?

Thanks!

**Comment by blag** [comment]
Digging into this a bit more, the import script seems to be tripping up [here](https://github.com/coderholic/django-cities/blob/master/cities/management/commands/cities.py#L847). As far as I'm aware, all Geonames postal code data contains latitude and longitude.

Double check that your data source has latitude and longitude coordinates. If you're importing from Geonames and it's missing coordinates, you can add coordinates through Geonames web interface and wait 24 hours for them to export another dump of their database.

If none of that works for you I can take a look at allowing postal code `location` fields to be `NULL`.

**Comment by blag** [comment]
I Googled around and [USAFA JBER Hospital](http://www.geonames.org/8486791/united-states-air-force-joint-base-elmendorf-richardson-hospital.html). I think somebody accidentally added it as a postal code which was then removed or fixed.

Either way, this is looking like a data bug, not a logic bug in this package. Closing.
