### ISSUE TITLE
migrate error.. django latest.. i belive readme is not enough

### ISSUE THREAD

**Issue by realsby** [coderholic/django-cities#158]
AttributeError: 'DatabaseOperations' object has no attribute 'geo_db_type'

**Comment by blag** [comment]
Are you using a database backend that supports GIS operations? See [this StackOverflow post](https://stackoverflow.com/questions/12538510/getting-databaseoperations-object-has-no-attribute-geo-db-type-error-when-do) for more.

See the documentation for [GeoDjango](https://docs.djangoproject.com/en/1.10/ref/contrib/gis/tutorial/#setting-up) for more.

**Comment by blag** [comment]
I have updated the README to include the GeoDjango requirement.

Closing, but feel free to reopen if using a GIS-enabled database doesn't fix it. Please include a full traceback, the `DATABASES` and `INSTALLED_APPS` settings from your project's `settings.py`, and any steps you've done to try to debug the problem. Thanks!
