### ISSUE TITLE
GB Postal Codes

### ISSUE THREAD

**Issue by phobos1** [coderholic/django-cities#164]
## Checklist

- [X] I have verified that I am using a GIS-enabled database, such as PostGIS or Spatialite.
- [X] I have verified that that issue exists against the `master` branch of django-cities.
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
Download GB Postal Codes

## Expected behavior
Postal Codes match the one of GB formats
@# #@@|@## #@@|@@# #@@|@@## #@@|@#@ #@@|@@#@ #@@|GIR0AA

## Actual behavior
Postal Codes did not match the one of GB formats
@# #@@|@## #@@|@@# #@@|@@## #@@|@#@ #@@|@@#@ #@@|GIR0AA

## P.S.
This is not bag.
Full postal codes for United Kingdom(GB) locate in http://download.geonames.org/export/zip/GB_full.csv.zip
For import this postal codes, need individual command

**Comment by blag** [comment]
I'm on mobile but there is an option to add postal codes even if they don't validate. If that doesn't work for you, you can add the postal code format (and regex) to the data at Geocities for the U.K. Country object.

Closing as not our bug (bug is upstream Inn geocities data and we have a workaround). Feel free to reopen if I have misunderstood the problem.
