### ISSUE TITLE
AlternativeNames queryset is empty after ...import=city

### ISSUE THREAD

**Issue by shalakhin** [coderholic/django-cities#168]
## Checklist

- [x] I have verified that I am using a GIS-enabled database, such as PostGIS or Spatialite.
- [x] I have verified that that issue exists against the `master` branch of django-cities.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

1) pip install
2) added to INSTALLED_APPS
3) added postgis extension to the database
4) ./manage.py migrate
5) running the script from the README to import=city (it ends successfully and I see the list of cities)
6) But no alternative names provided.

## Expected behavior

Alternative names should not be empty.

## Actual behavior

AlternativeName.objects.all() gives [] (empty list)

**Comment by blag** [comment]
This isn't a bug - you have to import alternative names separately from everything else.

Please try importing with `--import=alt_name` and report back. Closing for now.
