### ISSUE TITLE
Could not find the GDAL library

### ISSUE THREAD

**Issue by anuj9196** [coderholic/django-cities#196]
## Checklist

- [x] | Question
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] I have reduced the issue to the simplest possible case.

## Expected behavior

I only want little information like, `country name`, `country code`, `currency code`, `currency symbol`, `currency name` and their associated states data like `state name` and `state code`.

After installing `django-cities`, the only changes I'm made is

1. added `cities` to `INSTALLED_APPS`
2. added this setting item in `app.settings.py`.  
    `CITIES_INCLUDE_NUMERIC_ALTERNATIVE_NAMES = True`

When I run `manage.py migrate` it gives following error

> django.core.exceptions.ImproperlyConfigured: Could not find the  GDAL
> library (tried "gdal", "GDAL", "gdal2.2.0", "gdal2.1.0", "gdal2.0.0",
> "gdal1.11.0", "gdal1.10.0", "gdal1.9.0"). Is GDAL installed? If it is,
> try setting GDAL_LIBRARY_PATH in your settings.

Since I am not using any geographical data to plot on the map, etc. I do not want to install `GDAL` on my system.

**How can I use this plugin to have only `country` and `state` data without creating a mess-up in the database with data that is of no use to me?**

**Comment by blag** [comment]
> How can I use this plugin to have only country and state data without creating a mess-up in the database with data that is of no use to me?

This question is outside the scope of this project, and is completely and entirely unsupported by this project.

The only way you could really do this is to fork the project and remove all of the `location` fields from the database models.

At that point though, you've basically forked the project into another project, with your database models only containing a geographic hierarchy.

I think the easier path is to install GDAL on your computer.
