### ISSUE TITLE
How do I use localised country names?

### ISSUE THREAD

**Issue by TurnrDev** [coderholic/django-cities#201]
## Checklist

- [x] I have verified that I am using a GIS-enabled database, such as PostGIS or Spatialite.
- [x] I have verified that that issue exists against the `master` branch of django-cities.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

**Comment by frolovroman** [comment]
My version: 

1. Using custom model (myapp.City)
2. Add field name_local
3. create migration: 
```
cities = City.objects.filter(name_local__isnull=True)
for instance in cities:
    lang = instance.country.language_codes.split(',')[0]
    if lang:
        alt_name = instance.alt_names.filter(language_code=lang).order_by('-is_preferred').first()
        name_local = alt_name.name if alt_name else instance.name
        City.objects.filter(pk=instance.pk).update(name_local=name_local)
```
4. Same for Country
