### ISSUE TITLE
 ImportError: cannot import name 'python_2_unicode_compatible'

### ISSUE THREAD

**Issue by trademanthan** [coderholic/django-cities#215]
## Checklist

In Django 3.0.1 I am getting this import error python_2_unicode_compatible for django cities.

It should be
 'from six import python_2_unicode_compatible' 
in Django 3.0.1

- [ ] I have verified that I am using a GIS-enabled database, such as PostGIS or Spatialite.
- [ ] I have verified that that issue exists against the `master` branch of django-cities.
- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

**Comment by blag** [comment]
Please edit your post to fill in the issue template. I wrote the issue template for a reason, please use it.
