### ISSUE TITLE
ImportError: cannot import name 'python_2_unicode_compatible' from 'django.utils.encoding'

### ISSUE THREAD

**Issue by sweta-creoit** [coderholic/django-cities#217]
## Checklist

- [x] I have verified that I am using a GIS-enabled database, such as PostGIS or Spatialite.
- [x] I have verified that that issue exists against the `master` branch of django-cities.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

#Steps to reproduce

ERROR:(/cities/models.py)
from django.utils.encoding import python_2_unicode_compatible
ImportError: cannot import name 'python_2_unicode_compatible' from 'django.utils.encoding'

As per latest version of Django==Django==3.0.2, the python_2_unicode_compatible has been moved to six.py , need to get updated So that django-cities/models.py can pick from six.py package.

##Expected behavior

In /cities/models.py , the import should be:
from six import python_2_unicode_compatible

##Actual behavior

In /cities/models.py , the import is:
from django.utils.encoding import python_2_unicode_compatible

**Comment by blag** [comment]
Fixed by #214. I'll try to get around to updating the tests and merging that PR soon.
