### ISSUE TITLE
Make it possible to filter cities per country

### ISSUE THREAD

**Issue by jpic** [coderholic/django-cities#27]
Wouldn't it be useful to be able to specify the countries that you want to import the cities for ? Maybe it's not necessary to import all cities of all countries in all projects.

**Comment by bashu** [comment]
from https://github.com/coderholic/django-cities#configuration
```python
...
# Alternatively you can specify multiple filenames to process:
CITIES_FILES = {
    'city': {
       'filenames': ["US.zip", "GB.zip", ]
       'urls':     ['http://download.geonames.org/export/dump/'+'{filename}']
    },
}
...
```
