### ISSUE TITLE
Large number of SQL requests when creating a form with foreignkey to django-cities

### ISSUE THREAD

**Issue by renooble** [coderholic/django-cities#40]
Hi, 

I experience an tricky problem with creating forms with contain a dropdown menu with foreignkeys to django-cities. When the form is supposed to be created, the DB is hit with a large number of requests for 'cities_region' and 'cities_country'. Normally, I restrict the DB requests with select_related, but I do not seem to have luck with django-cities in this matter.

The model for my Item class contains the following code:

from cities.models import City 
class Item(models.Model): 
    name = models.CharField(...)
    location = models.ForeignKey(City, blank = True, null = True) 
    ...

and the views.py contain the class based view code:

from django.views.generic.edit import CreateView, UpdateView, DeleteView
from project.models import Project
class ItemCreate(CreateView):
     queryset = Item.objects.select_related('city', 'city__country', 'city__region').all()
     template_name = 'item_create_form.html'

When I now request the view class, I see an unlimited number of sql requests like below hitting the db and the page is not loading. It seems that the requests are created to fill the drop down box in the form menu.

SELECT "cities_country"."id", "cities_country"."name", "cities_country"."slug", "cities_country"."code", "cities_country"."population", "cities_country"."continent", "cities_country"."tld" FROM "cities_country" WHERE "cities_country"."id" = %s 
(2077456,)
SELECT "cities_region"."id", "cities_region"."name", "cities_region"."slug", "cities_region"."name_std", "cities_region"."code", "cities_region"."country_id" FROM "cities_region" WHERE "cities_region"."id" = %s 
(2147291,)

How are you restricting the requests to the DB when you include foreignkeys to the django-cities app?

Thanks for your thoughts.

**Comment by moorchegue** [comment]
I'm having a similar issue, which only affects django-cities tables (specifically city table queries create the biggest performance concern).

It's like select_relatad and prefetch_related are being ignored when working with these tables. It's a thing on two separate projects that use django-cities, so I'm inclined to blame it, but it's hard to tell for sure. Still trying to investigate.

Any hints?
