### ISSUE TITLE
Abbreviations of locations?

### ISSUE THREAD

**Issue by maltebeckmann** [coderholic/django-cities#71]
Hi,

Could it be that Django-Cities does not allow for abbreviations of locations? e.g. "Northrhein-Westphalen" (a German state) is commonly abbreviated as "NRW". The abbreviation can be found in Geonames for that state but we can't get it out on our end.

**Comment by coderholic** [comment]
You can optionally install locale data, which might include the abbreviations. Can you point me to where the abbreviation can be found in the geonames data?

**Comment by maltebeckmann** [comment]
Hi! Thanks for getting back to us - I found the abbreviations in the geonames.org and figured those would naturally be in the datasets. Check out the screenshot.
![geonames_org](https://cloud.githubusercontent.com/assets/230917/6184456/3d898f3a-b362-11e4-8fd3-cffd73d872ed.jpg)

**Comment by coderholic** [comment]
Oh sure, you can add these by adding `abbr` to CITIES_LOCALES in your settings file, and then running `./manage.py cities import=alt_names`

```
>>> region
<Region: North Rhine-Westphalia>
>>> region.alt_names.filter(language='abbr')
[<AlternativeName: NRW (abbr)>]

>>> AlternativeName.objects.filter(name='NRW')
[<AlternativeName: NRW (abbr)>]
>>> AlternativeName.objects.filter(name='NRW')[0].region_set.all()
[<Region: North Rhine-Westphalia>]
```

**Comment by maltebeckmann** [comment]
Cheers, Ben! We will give that a try! Thanks for this amazing app, it's making a big difference for us!

**Comment by coderholic** [comment]
No problem! Where are you using it?

**Comment by Tyrdall** [comment]
@coderholic Works like a charm. We're using it in an event webapp (not published yet).

**Comment by coderholic** [comment]
Great! Sounds cool, let me know when it's published! You should also check out http://ipinfo.io/developers - that might be useful for you too.

**Comment by Tyrdall** [comment]
Sure =) Ha, great, we're using Django's GeoIP at the moment.
