### ISSUE TITLE
Is there anyway to only import citynames/postalcodes for united states?

### ISSUE THREAD

**Issue by donnaloia** [coderholic/django-cities#74]
I ask this because I get a memory error during import.  Do 'import all' import every city from every country?  I was hoping a workaround would be to only import united states information.

The other work arounds to the memory issue seem very complicated.

Please advise.

**Comment by coderholic** [comment]
Yes import all imports data from all countries. There's no a command line option to import data for a single country, but one thing that should work is to import all country first (with import countries), and then delete all countries but the US. If you then import regions and then cities it'll only load those from the US.

**Comment by donnaloia** [comment]
Okay this seems to have worked, but how can i double check that the import was succesful and my database is populated with this information?

**Comment by donnaloia** [comment]
Also, to delete all countries but the US, can I do something like Countries.objects.all().exclude(name='United States").delete() ?

**Comment by donnaloia** [comment]
I wanted to double check first, because I'm scared to do the wrong thing and delete everything.

**Comment by donnaloia** [comment]
okay thank you so much.  I imported regions and cities like you told me.  Do I also need to run a seperate import for Postal codes?

**Comment by coderholic** [comment]
Yeah.

**Comment by donnaloia** [comment]
Last question, I did 'manage.py sqlclear cities' and then 'manage.py syncdb' to clear the table and start over again.  Next I did '/manage.py cities --import=Country' just like before but it just says INFO-file up to date.

For some reason Django thinks this information is already populated in the database even though I dropped the cities table, deleting everything.  Any advice on how to proceed?

**Comment by coderholic** [comment]
You need to do --force. I think it's up to date because it sees the
downloaded files.

**Comment by donnaloia** [comment]
I can now see countries has been populated in the database, but when i query PostalCode.objects.all() it returns an empty list...  I have used the --force --import=PostalCode and can see the information loading in the console window, it takes about 10-15 minutes, but after, PostalCode.objects.all() returns an empty list and all of my PostalCode queries that previously worked, now do not work because there is no PostalCode data.  Do you have any suggestions?  I already did sqlclear cities and tried to rebuild the tables and repopulate database by doing sqlclear and then syncdb.

**Comment by coderholic** [comment]
Did you import regions/cities/districts first?

**Comment by donnaloia** [comment]
No, what I have previously done is import country, import city and import postalcode  (in this order), and I had no problem.  should I do import in a different order than this?

**Comment by coderholic** [comment]
That order should be fine. Can you confirm that the city import worked, and you now have cities?

**Comment by donnaloia** [comment]
Yes, I can confirm city import worked.

**Comment by coderholic** [comment]
And you have a `CITIES_POSTAL_CODES` setting?

**Comment by donnaloia** [comment]
Yes, I do.

**Comment by donnaloia** [comment]
It's very strange because when I import PostalCode I can see the activity in the console window, it appears to be loading the information, but still there is nothing, I'm so confused.

**Comment by coderholic** [comment]
What do you see when you do a select count(1) from cities_postalcodes from
dbshell?

**Comment by donnaloia** [comment]
Nothing happens, it just returns to the next line.  This is my first time using dbshell, so maybe I am doing something incorrect.  I typed 'select count(1) from cities_postalcodes' and hit return.

**Comment by coderholic** [comment]
you need to add a semicolon on the end, eg:

```
# select count(1) from cities_postalcode;
 count
-------
 91307
(1 row)

#
```

**Comment by coderholic** [comment]
you need to add a semicolon on the end, eg:

```
# select count(1) from cities_postalcode;
count
-------
91307
(1 row)
```

**Comment by donnaloia** [comment]
count
__________
0
(1 row)

**Comment by coderholic** [comment]
Can you do the same for cities and countries?

**Comment by donnaloia** [comment]
count 250 for country.  count 140926 for cities.

**Comment by donnaloia** [comment]
Should I try 'sqlclear cities' again?

**Comment by coderholic** [comment]
Sure you could give it a try. Might also be worth trying with a completely new DB.

**Comment by donnaloia** [comment]
Well, after doing sqlclear and then force import (for the fourth time), I can now see PostalCodes, I'm not sure what the problem was before, but I don't even want to think about it anymore.
