### ISSUE TITLE
Third-party apps / extensions: django-airports

### ISSUE THREAD

**Issue by bashu** [coderholic/django-cities#76]
Thanks for django-cities, here is my small contribution https://github.com/bashu/django-airports
![screen shot 2015-03-27 at 14 10 40](https://cloud.githubusercontent.com/assets/144783/6864407/16110ef2-d48b-11e4-917e-849bddd82055.png)

**Comment by imposeren** [comment]
Maybe you should add some section to django-cities readme with link to related projects (with your project) and create pull request?

**Comment by bashu** [comment]
I will, thanks!
