### ISSUE TITLE
Python 3 Support?

### ISSUE THREAD

**Issue by mitsest** [coderholic/django-cities#78]
Hey,
is this on your to-do list? If not, I could fork it and run 2to3 (and debug) for you

Thanks!

**Comment by coderholic** [comment]
Sure thing, please do!

**Comment by DylanLukes** [comment]
It's diverged quite a bit, but yourlabs/django-cities-light is still a fork, and does have Python 3 support. If anything, that means it's possible.

It may be worth seeing what they've done to avoid problems.

**Comment by nbrede** [comment]
@mitsest Did you start / try it?

**Comment by mitsest** [comment]
nope, not yet. And I don't know if I 'll manage to find some time to do it :/
Sorry!

**Comment by illing2005** [comment]
I tried to include Python3 support in my fork. 
It seems to work but is not completly tested:
https://github.com/illing2005/django-cities

**Comment by mbambafd** [comment]
when run .manage.py --force --import=all i have strange error:
Exception: File not found and download failed: countryInfo.txt
i trying to solve it quickly if other person solve it before me please post.

**Comment by mbambafd** [comment]
ok solved !
the installation document not give this specification !
django-cities required 7 files(<a href="https://github.com/coderholic/django-cities/blob/master/cities/management/commands/cities.py">that's it</a>) it must copied in the django-cities package installation(something like this: site-package\django-cities\cities\data\...7 files
now i have another error:
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 404: character maps to <undefined>
i'm trying to solve it quickly ... if someone have solution before me please post.

**Comment by mbambafd** [comment]
solved UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 404: character!
we have to update cities.py
i have override all line contain open function
-- line 117
-- line 132
-- line 137
i added mode='r', encoding="utf8" (eg: before in line 117 we have >> file = open(os.path.join(self.data_dir, filename), 'wb') after become file = open(os.path.join(self.data_dir, filename), 'wb', mode='r', encoding="utf8"))
It all !

**Comment by mbambafd** [comment]
I take a time to manage all django-cities code to make it work on django 1.8 with python 3.4 correctly correctly !

**Comment by imposeren** [comment]
That's great! Have you made a pull request with your solution?

**Comment by mbambafd** [comment]
I code a much softer version of django -cities now (for django and + 1.6 . ) . The goal is to make it a close package for location-based applications and once I finish I post we try to validate it all together.

**Comment by bashu** [comment]
done, see related PR
