### ISSUE TITLE
Can I get city if I have a postal_code and country_name

### ISSUE THREAD

**Issue by asholok** [coderholic/django-cities#79]
Because I saw from example how to take list of postal_code if you have country and city. If it possible how does code look like?

**Comment by coderholic** [comment]
The example for getting postal codes by city from the readme is:
```
>>> PostalCode.objects.distance(City.objects.get(name='Mountain View', region__name='California').location).order_by('distance')[:5]
```

If you want a city from a postalcode you do pretty much the same:

```
>>> City.objects.distance(PostalCode.objects.get(code='94043').location).order_by('distance')[0]
```

**Comment by asholok** [comment]
Thx)

**Comment by asholok** [comment]
But what if two or more countries have the same code
for example:
City.objects.distance(PostalCode.objects.get(code='03803').location).order_by('distance')[0]

is it possible to use additional argument in get, like country or use filter?

**Comment by asholok** [comment]
I solve it with function
find_city(zip_code, country_name):
    zip_objs = PostalCode.objects.filter(code=zip_code)
    cities = [City.objects.distance(zip_obj.location).order_by('distance')[0] for zip_obj in zip_objs]

    for city in cities:
        if city.country.name == country_name:
            return city.name

**Comment by coderholic** [comment]
It'd be more efficient to solve it at the query level:
```
City.objects.distance(PostalCode.objects.get(code='03803', country__code='US').location).order_by('distance')[0]
```
