### ISSUE TITLE
Import issues

### ISSUE THREAD

**Issue by stringsonfire** [coderholic/django-cities#92]
The following stopped makemigrations from working with Django 1.8 and Python 3:

    File "C:\Python34\lib\site-packages\cities\models.py", line 4, in <module>
        from conf import settings
    ImportError: No module named 'conf'

    `.conf` works

    File "C:\Python34\lib\site-packages\cities\admin.py", line 2, in <module>
        from models import *
    ImportError: No module named 'models'

     `.models` works

I'm not sure if this would cause a problem for previous versions?

**Comment by stringsonfire** [comment]
See https://github.com/coderholic/django-cities/issues/94

**Comment by coderholic** [comment]
Can you confirm is this is still a problem or not with 0.4.2 from pypi?

**Comment by stringsonfire** [comment]
This was resolved when I installed the latest version from the github repo, so shouldn't be an issue with 0.4.2.
