### ISSUE TITLE
Outdated version on pypi? Last dated 2014-07-05

### ISSUE THREAD

**Issue by stringsonfire** [coderholic/django-cities#94]
On https://pypi.python.org/pypi/django-cities/0.4.1, the file says it was uploaded on `2014-07-05`. Given that there have been recent changes, does this mean that those changes aren't downloaded when using `pip` to install `django-cities`? In which case, does this need a version incrementation and a new upload?

It's also not listed under [`Python 3 Packages`](https://pypi.python.org/pypi?:action=browse&c=533&show=all)

**Comment by bashu** [comment]
+1

**Comment by coderholic** [comment]
Yeah apologies on this one - pypi was seriously outdated. I've just submitted the latest code as 0.4.2
