### ISSUE TITLE
Request: Country Flags

### ISSUE THREAD

**Issue by stringsonfire** [coderholic/django-cities#96]
Would this feature make sense for django-cities? The country select looks great in https://github.com/Bluefieldscom/intl-tel-input

**Comment by coderholic** [comment]
I wouldn't want to bundle something as part of this project, but there a few different projects you can use for flags. They often need just the country code. We use https://github.com/lafeber/world-flags-sprite on http://country.io (along with django-cities), and an alternative is http://lipis.github.io/flag-icon-css/
