### ISSUE TITLE
Import not working

### ISSUE THREAD

**Issue by cdvv7788** [coderholic/django-cities#98]
I am running python manage.py --import=all
It takes it like 5 seconds to stop. Nothing gets imported. Am i doing something wrong?

**Comment by coderholic** [comment]
Are you running `./manage.py cities --import=all`?

**Comment by cdvv7788** [comment]
Just copy/pasted that, same outcome.

**Comment by coderholic** [comment]
Copy the logging settings from https://github.com/coderholic/django-cities/blob/master/example/settings.py and then report back what the logs say

**Comment by cdvv7788** [comment]
INFO File up-to-date: countryInfo.txt
INFO File up-to-date: admin1CodesASCII.txt
INFO File up-to-date: admin2Codes.txt
INFO File up-to-date: cities5000.zip
INFO File up-to-date: cities5000.zip
INFO File up-to-date: alternateNames.zip
INFO File up-to-date: allCountries.zip

From what i remember (used this in the past) that command should extract and dump that data to my db, right?

**Comment by cdvv7788** [comment]
It inserted the data. I manually deleted those files from the package (site-packages/cities/data/*).
It seems to be comparing server files with local files and ignoring update if they are equal.
Maybe i imported that in the past and is using a cached version of the package, which contains that data (is unlikely but can't discard).
Are you able to reproduce the issue or is it just me? I am using python3.4.
What about providing some mechanism to improve that verification? We could add some table to keep track of last import. That would fail too if tables are manually deleted, but would be more reliable than current method.

**Comment by coderholic** [comment]
`--force` forces the import

**Comment by cdvv7788** [comment]
Oh true, dumb me. thanks.

**Comment by ysfjwd** [comment]
do you mean
```
./manage.py cities --import=all --force
```

to force import?

//ysf

**Comment by cdvv7788** [comment]
Yeah, thats the whole command

**Comment by ysfjwd** [comment]
thanks
